import { makeKV, R, suite, call, worker } from "./lib.mjs";
const { ok, done } = suite();
const env = { AUTH_TOKEN: "tok", CONDUCTOR: makeKV(), GROQ_API_KEY: "g", BUILDER_URL: "https://builder", BUILDER_TOKEN: "bt" };
const plan = { user_inputs: [{ name: "city", type: "string" }], subgoals: [{ id: "sg1", title: "Get weather", does: "get the weather forecast for a city", inputs: [{ name: "city", type: "string", from: "user.city" }], outputs: [{ name: "text", type: "string" }], final: true }] };
globalThis.fetch = async (url, o = {}) => {
  url = String(url);
  if (url.endsWith("/models")) return R({ data: [{ id: "openai/gpt-oss-120b" }] });
  if (url.includes("groq.com") && url.endsWith("/chat/completions")) return R({ choices: [{ message: { content: JSON.stringify(plan) } }] });
  if (url.endsWith("/plan")) return R({ status: "ok", id: "bp1" });
  if (url.endsWith("/run")) return R({ status: "dry_run_ok", report: [{ node: "n1", ok: true }], outputs: { n1: { text: "Sunny" } } });
  if (url.endsWith("/recipes")) return R({ recipes: [] });
  return R({ error: "unexpected " + url }, 500);
};
let r = await worker.fetch(new Request("https://c/jobs"), env);
ok(r.status === 401, "no token -> 401");
r = await worker.fetch(new Request("https://c/jobs", { headers: { authorization: "Bearer wrong" } }), env);
ok(r.status === 401, "wrong token -> 401");
const page = await (await worker.fetch(new Request("https://c/"), env)).text();
let syntax = true; try { new Function(page.match(/<script>([\s\S]*?)<\/script>/)[1]); } catch (e) { syntax = false; console.log(e.message); }
ok(syntax && page.includes("Split the goal"), "the page loads without a token and its script parses");
let x = await call(env, "/decompose", "POST", { goal: "weather" });
ok(x.status === 200 && x.d.status === "ok" && x.d.plan_id, "POST /decompose returns a checked split and an id");
x = await call(env, "/job", "POST", { plan_id: x.d.plan_id, inputs: {}, dry: true });
ok(x.status === 500 && /missing values: city/.test(x.d.error), "a job without its values is refused with a clear message");
const pid = (await call(env, "/decompose", "POST", { goal: "weather" })).d.plan_id;
x = await call(env, "/job", "POST", { plan_id: pid, goal: "weather", inputs: { city: "Manila" }, dry: true });
const jid = x.d.job_id; ok(jid && x.d.dry === true, "a job is created and defaults to dry run");
x = await call(env, "/job/" + jid + "/advance", "POST", {});
ok(x.d.status === "done" && x.d.steps[0].status === "done", "advance runs the step through the builder");
x = await call(env, "/job/" + jid + "?full=1"); ok(x.d.steps[0].output.text === "Sunny", "full=1 returns the complete output");
x = await call(env, "/jobs"); ok(x.d.jobs.length === 1 && x.d.jobs[0].status === "done", "jobs are listed");
x = await call(env, "/modules/import", "POST", {}); ok(x.d.ok && Array.isArray(x.d.added), "import route works");
await call(env, "/decompose", "POST", {}).then((r) => ok(r.status === 400, "decompose without a goal -> 400"));
const m = { id: "mm", status: "candidate", does: "d", inputs: [], outputs: [], proof: { ok_runs: 0, real_runs: 0, ok_inputs: [] }, notes: [] };
await env.CONDUCTOR.put("mod:mm", JSON.stringify(m));
x = await call(env, "/module/mm/status", "POST", { status: "proven" }); ok(x.d.status === "proven", "the owner can mark a module proven");
x = await call(env, "/module/mm/status", "POST", { status: "bogus" }); ok(x.status === 400, "an invalid status is refused");
const { default: w } = await import("../src/index.js");
let ran = false; await w.scheduled({}, env, { waitUntil: (p) => { ran = true; return p; } }); ok(ran, "the cron handler runs");
done();
